--------------------------------------------------------
--  File created - Monday-May-06-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence FORECAST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BATMAN"."FORECAST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOCATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BATMAN"."LOCATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PERSON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BATMAN"."PERSON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REPAIRLOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BATMAN"."REPAIRLOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SALARY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BATMAN"."SALARY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STATIONREADING_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BATMAN"."STATIONREADING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STATION_HIST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BATMAN"."STATION_HIST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BATMAN"."STATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "BATMAN"."CUSTOMER" 
   (	"PERSONID" NUMBER(6,0), 
	"SUBSCRIPTION_TYPE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "BATMAN"."EMPLOYEE" 
   (	"PERSONID" NUMBER(6,0), 
	"POSITIONTITLE" VARCHAR2(25 BYTE), 
	"POSITIONTYPE" CHAR(1 BYTE), 
	"VATNUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORECAST
--------------------------------------------------------

  CREATE TABLE "BATMAN"."FORECAST" 
   (	"FORECAST_ID" VARCHAR2(16 BYTE), 
	"FORECASTDATE" DATE, 
	"LOCATIONID" NUMBER(6,0), 
	"TEMPRATURE" NUMBER(6,8), 
	"AIR_PRESSURE" NUMBER(6,8), 
	"HUMIDITY" NUMBER(6,8), 
	"AMBIENT_LIGHT" NUMBER(6,8), 
	"ALTITUDE" NUMBER(6,8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "BATMAN"."LOCATION" 
   (	"LOCATIONID" NUMBER(6,0), 
	"LOCATIONNAME" VARCHAR2(25 BYTE), 
	"COLUMN1" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "BATMAN"."PERSON" 
   (	"PERSONID" NUMBER(6,0), 
	"IDNUMBER" VARCHAR2(15 BYTE), 
	"FIRSTNAME" VARCHAR2(25 BYTE), 
	"LASTNAME" VARCHAR2(25 BYTE), 
	"PHONENUMBER" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(55 BYTE), 
	"PERSONTYPE" CHAR(1 BYTE), 
	"USERNAME" VARCHAR2(55 BYTE), 
	"PASSWORD" VARCHAR2(55 BYTE), 
	"ACTIVE_USER" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPAIRLOG
--------------------------------------------------------

  CREATE TABLE "BATMAN"."REPAIRLOG" 
   (	"REPAIRID" NUMBER(10,0), 
	"PERSONID" NUMBER(6,0), 
	"STATIONID" NUMBER(6,0), 
	"DATE_OF" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALARY
--------------------------------------------------------

  CREATE TABLE "BATMAN"."SALARY" 
   (	"SALARYID" NUMBER(6,0), 
	"PERSONID" NUMBER(6,0), 
	"AMOUNT" NUMBER(10,2), 
	"DATEPAID" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATION
--------------------------------------------------------

  CREATE TABLE "BATMAN"."STATION" 
   (	"STATIONID" NUMBER(6,0), 
	"STATUS" VARCHAR2(55 BYTE), 
	"LOCATIONID" NUMBER(6,0), 
	"COORDINATES" VARCHAR2(128 BYTE), 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATIONREADING
--------------------------------------------------------

  CREATE TABLE "BATMAN"."STATIONREADING" 
   (	"READING_ID" NUMBER(16,0), 
	"STATIONID" NUMBER(6,0), 
	"READINGLOCATION" VARCHAR2(25 BYTE), 
	"READING_DATE" DATE DEFAULT sysdate, 
	"TEMPRATURE" NUMBER(6,8), 
	"AIR_PRESSURE" NUMBER(6,8), 
	"AMBIENT_LIGHT" NUMBER(6,8), 
	"HUMIDITY" NUMBER(6,8), 
	"ALTITUDE" NUMBER(6,8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATION_HIST
--------------------------------------------------------

  CREATE TABLE "BATMAN"."STATION_HIST" 
   (	"HIST_ID" NUMBER(6,0), 
	"LOCATIONID" NUMBER(6,0), 
	"COORDINATES" VARCHAR2(128 BYTE), 
	"STATIONID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUBSCRIPTION
--------------------------------------------------------

  CREATE TABLE "BATMAN"."SUBSCRIPTION" 
   (	"SUBSCRIPTION_TYPE" NUMBER(6,0), 
	"MONTHLY_PRICE" NUMBER(6,2), 
	"NAME" VARCHAR2(12 BYTE), 
	"INTERVAL_TIME" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TECHNICIAN
--------------------------------------------------------

  CREATE TABLE "BATMAN"."TECHNICIAN" 
   (	"PERSONID" NUMBER(6,0), 
	"HARDWARE_YES" NUMBER(1,0), 
	"SOFTWARE_YES" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SALARY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."SALARY_PK" ON "BATMAN"."SALARY" ("SALARYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMAIL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."EMAIL_UK" ON "BATMAN"."PERSON" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."CUSTOMER_PK" ON "BATMAN"."CUSTOMER" ("PERSONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUBSCRIPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."SUBSCRIPTION_PK" ON "BATMAN"."SUBSCRIPTION" ("SUBSCRIPTION_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."STATION_PK" ON "BATMAN"."STATION" ("STATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FORECAST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."FORECAST_PK" ON "BATMAN"."FORECAST" ("FORECAST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."EMPLOYEE_PK" ON "BATMAN"."EMPLOYEE" ("PERSONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."PERSON_PK" ON "BATMAN"."PERSON" ("PERSONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STATIONREADING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."STATIONREADING_PK" ON "BATMAN"."STATIONREADING" ("READING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."LOCATION_PK" ON "BATMAN"."LOCATION" ("LOCATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TECHNICIAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."TECHNICIAN_PK" ON "BATMAN"."TECHNICIAN" ("PERSONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPAIRLOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."REPAIRLOG_PK" ON "BATMAN"."REPAIRLOG" ("REPAIRID", "PERSONID", "STATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STATION_HIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATMAN"."STATION_HIST_PK" ON "BATMAN"."STATION_HIST" ("HIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger FORECAST_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BATMAN"."FORECAST_TRG" 
BEFORE INSERT ON FORECAST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.FORECAST_ID IS NULL THEN
      SELECT FORECAST_SEQ.NEXTVAL INTO :NEW.FORECAST_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BATMAN"."FORECAST_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BATMAN"."LOCATION_TRG" 
BEFORE INSERT ON LOCATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LOCATIONID IS NULL THEN
      SELECT LOCATION_SEQ.NEXTVAL INTO :NEW.LOCATIONID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BATMAN"."LOCATION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PERSON_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BATMAN"."PERSON_TRG" 
BEFORE INSERT ON PERSON 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PERSONID IS NULL THEN
      SELECT PERSON_SEQ.NEXTVAL INTO :NEW.PERSONID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BATMAN"."PERSON_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REPAIRLOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BATMAN"."REPAIRLOG_TRG" 
BEFORE INSERT ON REPAIRLOG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.REPAIRID IS NULL THEN
      SELECT REPAIRLOG_SEQ.NEXTVAL INTO :NEW.REPAIRID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BATMAN"."REPAIRLOG_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SALARY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BATMAN"."SALARY_TRG" 
BEFORE INSERT ON SALARY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SALARYID IS NULL THEN
      SELECT SALARY_SEQ.NEXTVAL INTO :NEW.SALARYID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BATMAN"."SALARY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STATIONREADING_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BATMAN"."STATIONREADING_TRG" 
BEFORE INSERT ON STATIONREADING 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.READING_ID IS NULL THEN
      SELECT STATIONREADING_SEQ.NEXTVAL INTO :NEW.READING_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BATMAN"."STATIONREADING_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STATION_HIST_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BATMAN"."STATION_HIST_TRG" 
BEFORE INSERT ON STATION_HIST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.HIST_ID IS NULL THEN
      SELECT STATION_HIST_SEQ.NEXTVAL INTO :NEW.HIST_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BATMAN"."STATION_HIST_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BATMAN"."STATION_TRG" 
BEFORE INSERT ON STATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.STATIONID IS NULL THEN
      SELECT STATION_SEQ.NEXTVAL INTO :NEW.STATIONID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BATMAN"."STATION_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "BATMAN"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("PERSONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."EMPLOYEE" MODIFY ("PERSONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "BATMAN"."PERSON" ADD CONSTRAINT "EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("PERSONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."PERSON" MODIFY ("ACTIVE_USER" NOT NULL ENABLE);
  ALTER TABLE "BATMAN"."PERSON" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BATMAN"."PERSON" MODIFY ("PERSONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "BATMAN"."LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("LOCATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."LOCATION" MODIFY ("LOCATIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORECAST
--------------------------------------------------------

  ALTER TABLE "BATMAN"."FORECAST" ADD CONSTRAINT "FORECAST_PK" PRIMARY KEY ("FORECAST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."FORECAST" MODIFY ("FORECAST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALARY
--------------------------------------------------------

  ALTER TABLE "BATMAN"."SALARY" ADD CONSTRAINT "SALARY_PK" PRIMARY KEY ("SALARYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."SALARY" MODIFY ("DATEPAID" NOT NULL ENABLE);
  ALTER TABLE "BATMAN"."SALARY" MODIFY ("SALARYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TECHNICIAN
--------------------------------------------------------

  ALTER TABLE "BATMAN"."TECHNICIAN" ADD CONSTRAINT "TECHNICIAN_PK" PRIMARY KEY ("PERSONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."TECHNICIAN" MODIFY ("PERSONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATIONREADING
--------------------------------------------------------

  ALTER TABLE "BATMAN"."STATIONREADING" ADD CONSTRAINT "STATIONREADING_PK" PRIMARY KEY ("READING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."STATIONREADING" MODIFY ("READING_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBSCRIPTION
--------------------------------------------------------

  ALTER TABLE "BATMAN"."SUBSCRIPTION" ADD CONSTRAINT "SUBSCRIPTION_PK" PRIMARY KEY ("SUBSCRIPTION_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."SUBSCRIPTION" MODIFY ("SUBSCRIPTION_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPAIRLOG
--------------------------------------------------------

  ALTER TABLE "BATMAN"."REPAIRLOG" ADD CONSTRAINT "REPAIRLOG_PK" PRIMARY KEY ("REPAIRID", "PERSONID", "STATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."REPAIRLOG" MODIFY ("STATIONID" NOT NULL ENABLE);
  ALTER TABLE "BATMAN"."REPAIRLOG" MODIFY ("PERSONID" NOT NULL ENABLE);
  ALTER TABLE "BATMAN"."REPAIRLOG" MODIFY ("REPAIRID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATION_HIST
--------------------------------------------------------

  ALTER TABLE "BATMAN"."STATION_HIST" ADD CONSTRAINT "STATION_HIST_PK" PRIMARY KEY ("HIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."STATION_HIST" MODIFY ("HIST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATION
--------------------------------------------------------

  ALTER TABLE "BATMAN"."STATION" ADD CONSTRAINT "STATION_PK" PRIMARY KEY ("STATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."STATION" MODIFY ("STATIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "BATMAN"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("PERSONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN"."CUSTOMER" MODIFY ("PERSONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "BATMAN"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_FK" FOREIGN KEY ("SUBSCRIPTION_TYPE")
	  REFERENCES "BATMAN"."SUBSCRIPTION" ("SUBSCRIPTION_TYPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORECAST
--------------------------------------------------------

  ALTER TABLE "BATMAN"."FORECAST" ADD CONSTRAINT "FORECAST_FK" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "BATMAN"."LOCATION" ("LOCATIONID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPAIRLOG
--------------------------------------------------------

  ALTER TABLE "BATMAN"."REPAIRLOG" ADD CONSTRAINT "REPAIR_FK_STATION" FOREIGN KEY ("STATIONID")
	  REFERENCES "BATMAN"."STATION" ("STATIONID") ENABLE;
  ALTER TABLE "BATMAN"."REPAIRLOG" ADD CONSTRAINT "REPAIR_FK_TECH" FOREIGN KEY ("PERSONID")
	  REFERENCES "BATMAN"."TECHNICIAN" ("PERSONID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALARY
--------------------------------------------------------

  ALTER TABLE "BATMAN"."SALARY" ADD CONSTRAINT "SALARY_FK" FOREIGN KEY ("PERSONID")
	  REFERENCES "BATMAN"."EMPLOYEE" ("PERSONID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATION
--------------------------------------------------------

  ALTER TABLE "BATMAN"."STATION" ADD CONSTRAINT "STATION_LOC_FK" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "BATMAN"."LOCATION" ("LOCATIONID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATIONREADING
--------------------------------------------------------

  ALTER TABLE "BATMAN"."STATIONREADING" ADD CONSTRAINT "READING_FK" FOREIGN KEY ("STATIONID")
	  REFERENCES "BATMAN"."STATION" ("STATIONID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATION_HIST
--------------------------------------------------------

  ALTER TABLE "BATMAN"."STATION_HIST" ADD CONSTRAINT "STATION_HIST_FK" FOREIGN KEY ("STATIONID")
	  REFERENCES "BATMAN"."STATION" ("STATIONID") ENABLE;
