--Add PERSON--
INSERT INTO "PERSON" (PERSONID, IDNUMBER, FIRSTNAME, LASTNAME, PHONENUMBER, EMAIL, PERSONTYPE, USERNAME, PASSWORD, ACTIVE_USER)
  VALUES (1, '971245', 'Morne', 'Venter', '0715724319', 'morne@mail.com', 'E', 'morVen', 'pass123', '1');
INSERT INTO "PERSON" (PERSONID, IDNUMBER, FIRSTNAME, LASTNAME, PHONENUMBER, EMAIL, PERSONTYPE, USERNAME, PASSWORD, ACTIVE_USER)
  VALUES (2, '980704', 'Eon', 'Viljoen', '0123649821', 'eon@mail.com', 'C', 'eonBoy', 'secret123', '1');
INSERT INTO "PERSON" (PERSONID, IDNUMBER, FIRSTNAME, LASTNAME, PHONENUMBER, EMAIL, PERSONTYPE, USERNAME, PASSWORD, ACTIVE_USER)
  VALUES (3, '950510', 'Coenraad', 'Human', '0123592134', 'coen@mail.com', 'E', 'coenPenguin', 'megaSecret', '1');

--add SUBSCRIPTION--
INSERT INTO "SUBSCRIPTION" (SUBSCRIPTION_TYPE, MONTHLY_PRICE, NAME, INTERVAL_TIME) VALUES (1, 99.99, 'Gold', 15);
INSERT INTO "SUBSCRIPTION" (SUBSCRIPTION_TYPE, MONTHLY_PRICE, NAME, INTERVAL_TIME) VALUES (2, 59.99, 'Silver', 30);
INSERT INTO "SUBSCRIPTION" (SUBSCRIPTION_TYPE, MONTHLY_PRICE, NAME, INTERVAL_TIME) VALUES (3, 29.99, 'Bronze', 60);

--add CUSTOMER
INSERT INTO "CUSTOMER" (PERSONID, SUBSCRIPTION_TYPE, PERSONTYPE) VALUES (2, 2, 'C');

--add EMPLOYEE
INSERT INTO "EMPLOYEE" (PERSONID, POSITIONTITLE, POSITIONTYPE, VATNUMBER, PERSONTYPE) VALUES (1, 'Head Manager', 'M', '1515415', 'E');
INSERT INTO "EMPLOYEE" (PERSONID, POSITIONTITLE, POSITIONTYPE, VATNUMBER, PERSONTYPE) VALUES (3, 'Technician', 'T', '1541515', 'E');

--add TECHNICIAN
INSERT INTO "TECHNICIAN" (PERSONID, HARDWARE_YES, SOFTWARE_YES, POSITIONTYPE) VALUES (3, 1, 0, 'T');

--add SALARY
INSERT INTO "SALARY" (PERSONID, AMOUNT, DATEPAID) VALUES (1, 30000.50, TO_DATE('2018-01-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SALARY" (PERSONID, AMOUNT, DATEPAID) VALUES (3, 15000.40, TO_DATE('2019-05-14 17:23:30', 'YYYY-MM-DD HH24:MI:SS'));

--add  LOCATION
INSERT INTO "LOCATION" (LOCATIONID, LOCATIONNAME, PROVINCE) VALUES (1, 'Anatombi', 'North West');
INSERT INTO "LOCATION" (LOCATIONID, LOCATIONNAME, PROVINCE) VALUES (2, '7 Postma Street', 'North West');

--add STATION
INSERT INTO "STATION" (STATIONID, STATUS, LOCATIONID, COORDINATES, ISACTIVE) VALUES (1, 'Working', 1, 'x:4574,23232;y:347864,23', 1);
INSERT INTO "STATION" (STATIONID, STATUS, LOCATIONID, COORDINATES, ISACTIVE) VALUES (2, 'Offline', 1, 'x:4574,22;y:34764,23', 0);
INSERT INTO "STATION" (STATIONID, STATUS, LOCATIONID, COORDINATES, ISACTIVE) VALUES (3, 'Working', 2, 'x:34737,123;y:374,534', 1);

--add STATION_HIST
DEFINE x = 1
INSERT INTO "STATION_HIST" (STATIONID, LOCATIONID, COORDINATES)
VALUES (&x, (SELECT station.locationid
            FROM station
            WHERE station.stationid = &x), (SELECT station.coordinates
                                           FROM station
                                           WHERE station.stationid = &x));
UNDEFINE x

DEFINE x = 1
INSERT INTO "STATION_HIST" (STATIONID, LOCATIONID, COORDINATES)
VALUES (&x, (SELECT station.locationid
            FROM station
            WHERE station.stationid = &x), (SELECT station.coordinates
                                           FROM station
                                           WHERE station.stationid = &x));
UNDEFINE x

DEFINE x = 2
INSERT INTO "STATION_HIST" (STATIONID, LOCATIONID, COORDINATES)
VALUES (&x, (SELECT station.locationid
            FROM station
            WHERE station.stationid = &x), (SELECT station.coordinates
                                           FROM station
                                           WHERE station.stationid = &x));
UNDEFINE x


--add FORECAST
INSERT INTO "FORECAST" (FORECASTDATE, LOCATIONID, TEMPRATURE, AIR_PRESSURE, HUMIDITY, AMBIENT_LIGHT, ALTITUDE)
VALUES (TO_DATE('2019-05-21 17:52:08', 'YYYY-MM-DD HH24:MI:SS'), 2, 32, 874.6, 0.54, 0.08, 1385.1);

--REPAIRLOG
INSERT INTO "REPAIRLOG" (PERSONID, STATIONID, DATE_OF, DESCRIPTION) VALUES (3, 2, TO_DATE('2019-05-22 18:04:03', 'YYYY-MM-DD HH24:MI:SS'), 'Fixed light sensor.');
INSERT INTO "REPAIRLOG" (PERSONID, STATIONID, DATE_OF, DESCRIPTION) VALUES (3, 1, TO_DATE('2019-07-12 18:04:03', 'YYYY-MM-DD HH24:MI:SS'), 'Fixed faulty battery.');

--STATIONREADING
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.19, 871.76, 0.02, 0.32, 1305.23);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.17, 871.75, 0.02, 0.32, 1305.32);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.16, 871.76, 0.02, 0.32, 1305.24);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.19, 871.76, 0.02, 0.32, 1305.25);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.20, 871.78, 0.02, 0.32, 1305.00);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.21, 871.78, 0.01, 0.32, 1305.04);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.20, 871.76, 0.01, 0.32, 1305.18);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.21, 871.77, 0.02, 0.32, 1305.12);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.21, 871.77, 0.02, 0.32, 1305.16);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.20, 871.77, 0.02, 0.32, 1305.11);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.21, 871.75, 0.02, 0.32, 1305.29);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.23, 871.77, 0.02, 0.32, 1305.11);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.22, 871.79, 0.02, 0.32, 1304.98);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.23, 871.78, 0.02, 0.32, 1305.01);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.23, 871.78, 0.02, 0.32, 1305.01);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 21.34, 871.78, 0.02, 0.36, 1305.08);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 22.23, 871.72, 0.02, 0.58, 1305.57);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 22.48, 871.77, 0.02, 0.69, 1305.11);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 22.40, 871.76, 0.02, 0.62, 1305.21);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 22.35, 871.77, 0.02, 0.37, 1305.17);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 22.34, 871.75, 0.02, 0.34, 1305.35);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 22.30, 871.74, 0.02, 0.33, 1305.39);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 22.24, 871.78, 0.46, 0.32, 1305.01);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 22.20, 871.75, 1.00, 0.32, 1305.30);
INSERT INTO "STATIONREADING" (STATIONID, READINGLOCATION, READING_DATE, TEMPRATURE, AIR_PRESSURE, AMBIENT_LIGHT, HUMIDITY, ALTITUDE) VALUES (1, 1,sysdate, 22.13, 871.71, 0.02, 0.32, 1305.68);
